### ISSUE TITLE
Self Contained or external dependencies

### ISSUE THREAD

**Issue by langedb** [wgthom/groovysh4grouper#5]
@wgthom, should we try to bundle Groovy in with this & make it completely self-contained or make the sysadmin install Groovy separately?  The unix guy in me likes the system-provided groovy, but those in the windows world (which we will have to deal with before the project can fully accept this) makes me think it may be better to bundle Groovy and make this thing as stand-alone as possible.

Thoughts?

**Comment by wgthom** [comment]
not sure. hopefully we can tackle this as we incorporated it into the Grouper distro
